### ISSUE TITLE
Can't find package libxml2

### ISSUE THREAD

**Issue by ThomasMG** [UPPAALModelChecker/utap#34]
When building I get the following error
```
CMake Error at CMakeLists.txt:26 (find_package):
  Could not find a configuration file for package "libxml2" that is
  compatible with requested version "2.9.14".
  
  The following configuration files were considered but not accepted:
    /usr/local/lib/cmake/libxml2/libxml2-config.cmake, version: unknown
```
Even though I installed libxml 2.9.14 from https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.9.14

However if I change the CMakeLists to use `find_package(LibXml2 ...` instead of `find_package(libxml2 ...` (to always use the darwin case) I get no error installing and using UTAP. This is on Ubuntu 22.04.1.

**Comment by thorulf4** [comment]
Did you try installing libxml from the getlibs script?
Its located in `./getlibs/getlibs.sh`

Im not sure but i suspect that this happens because cmake expects to find the libraries in a specific folder that the getlibs scripts knows about

**Comment by ThomasMG** [comment]
> Did you try installing libxml from the getlibs script? Its located in `./getlibs/getlibs.sh`
> 
> Im not sure but i suspect that this happens because cmake expects to find the libraries in a specific folder that the getlibs scripts knows about

The problem is that it works just fine with the name changed. It is not that it can't find it at all. The correct version of libxml2 is installed in a location that `find_package` already searches.

**Comment by thorulf4** [comment]
This isnt really a problem. Its an intentional decision that we dont pick up libxml from `/usr/local/lib/..`, which is seemingly acheived by using a lowercase "libxml2" package name. CMake is configured to only pickup libxml if its installed by the getlibs script.

Looking over the readme I can see its very outdated, which ill look at fixing soon #35

For now I recommend running the getlibs script with `./getlibs/getlibs.sh linux64` and then running the compile.sh script afterwards. If this still doesnt work please let me know.

**Comment by ThomasMG** [comment]
But then having UTAP as a non-local dependency is a really convoluted process. Is there a reason that libxml2 has to be installed through this specific script?

**Comment by thorulf4** [comment]
Hmm, Ill have to take this up for discussion. But I'm under the impression that this is done to improve reproducibility and minimize local configuration work to get UTAP compiling.

Unfortunately I dont have the experience to give tips on how to setup UTAP as a dependency in nice way..

**Comment by thorulf4** [comment]
> I just think it makes sense to pick up libxml2 if it is already installed.
Yeah i agree with this sentiment, and ill be looking into whether we can improve this

**Comment by mikucionisaau** [comment]
There is a chain of reasons:
1) we compile `libxml2` separately due to configuration/version management (libxml2 has lots of options and there are many different versions, we cannot control what is installed and what's not, it's great if it works for you).
2) `libXml` vs `libxml`: the issue is that libxml2 does not use `cmake` scripts to build and export the configuration. It's getting better, but there are still many inconsistencies with macOS specifically: if you use one variant it works on Linux and it does not on mac, and then the other way around.
3) we stick to gcc-10 because it is a common denominator when cross-compiling for Windows using MinGW.
